import os
import threading
import time
import requests
import logging
from urllib.parse import quote
from flask import Flask, redirect, Response
# 🔴 引入 P115Client 用于初始化连接
from p115 import P115FileSystem, P115Client

# ================= 配置加载 =================
COOKIE = os.environ.get("P115_COOKIE")
if not COOKIE:
    print("FATAL: P115_COOKIE environment variable is missing!")
    exit(1)

SOURCE_DIR = os.environ.get("SOURCE_DIR", "/Music")
OUTPUT_DIR = "/output"
HOST_URL = os.environ.get("HOST_URL", "http://127.0.0.1:8000").rstrip('/') 
SCAN_INTERVAL = int(os.environ.get("SCAN_INTERVAL", 3600))

IMAGE_EXTS = ('.jpg', '.jpeg', '.png', '.tbn')
MUSIC_EXTS = ('.mp3', '.flac', '.wav', '.m4a', '.dsf', '.dff', '.ape', '.wma', '.aac')

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

app = Flask(__name__)
fs = None

def login_115():
    """初始化或重置 115 连接"""
    global fs
    try:
        # 🔴 修正：先创建 Client，再创建 FileSystem
        # 这样可以确保 cookie 正确传递并验证
        client = P115Client(cookie=COOKIE)
        fs = P115FileSystem(client)
        
        logger.info("115 Login Successful")
        return True
    except Exception as e:
        logger.error(f"Login Failed: {e}")
        return False

def sync_image(file_info, local_dir):
    """同步图片"""
    filename = file_info['name']
    local_path = os.path.join(local_dir, filename)
    remote_size = int(file_info.get('size', 0))
    
    if os.path.exists(local_path):
        if os.path.getsize(local_path) == remote_size:
            return 
    
    logger.info(f"Downloading Image: {filename}")
    try:
        url = fs.get_url(file_info['pickcode'])
        r = requests.get(url, stream=True, timeout=30)
        if r.status_code == 200:
            with open(local_path, 'wb') as f:
                for chunk in r.iter_content(1024*1024):
                    f.write(chunk)
    except Exception as e:
        logger.error(f"Error downloading image {filename}: {e}")

def create_nfo(filename, local_dir, album_name="Unknown", artist_name="Unknown"):
    """生成 NFO"""
    nfo_name = os.path.splitext(filename)[0] + ".nfo"
    nfo_path = os.path.join(local_dir, nfo_name)
    
    if os.path.exists(nfo_path):
        return

    title = os.path.splitext(filename)[0]
    xml_content = f"""<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<musicvideo>
  <title>{title}</title>
  <artist>{artist_name}</artist>
  <album>{album_name}</album>
  <plot>Generated by 115-Strm-Service</plot>
</musicvideo>"""
    
    try:
        with open(nfo_path, 'w', encoding='utf-8') as f:
            f.write(xml_content)
    except Exception as e:
        logger.error(f"Error creating NFO: {e}")

def scanner_task():
    """后台扫描线程"""
    while True:
        if fs is None:
            if not login_115():
                time.sleep(60)
                continue

        logger.info(f"--- Starting Scan: {SOURCE_DIR} ---")
        try:
            for root, dirs, files in fs.walk(SOURCE_DIR):
                rel_path = os.path.relpath(root, SOURCE_DIR)
                if rel_path == ".":
                    local_dir = OUTPUT_DIR
                else:
                    local_dir = os.path.join(OUTPUT_DIR, rel_path)
                
                if not os.path.exists(local_dir):
                    os.makedirs(local_dir, exist_ok=True)

                album_name = os.path.basename(root)
                try:
                    artist_name = os.path.basename(os.path.dirname(root))
                except:
                    artist_name = "Unknown"

                for file in files:
                    fname = file['name']
                    ext = os.path.splitext(fname)[1].lower()

                    if ext in IMAGE_EXTS:
                        sync_image(file, local_dir)
                    
                    elif ext in MUSIC_EXTS:
                        strm_name = os.path.splitext(fname)[0] + ".strm"
                        strm_path = os.path.join(local_dir, strm_name)
                        
                        safe_filename = quote(fname)
                        pickcode = file['pickcode']
                        file_url = f"{HOST_URL}/play/{pickcode}/{safe_filename}"
                        
                        if not os.path.exists(strm_path):
                            with open(strm_path, 'w', encoding='utf-8') as f:
                                f.write(file_url)
                            logger.info(f"Generated: {strm_name}")
                        else:
                            with open(strm_path, 'r', encoding='utf-8') as f:
                                content = f.read()
                            if content != file_url:
                                with open(strm_path, 'w', encoding='utf-8') as f:
                                    f.write(file_url)
                                logger.info(f"Updated: {strm_name}")

                        create_nfo(fname, local_dir, album_name, artist_name)
            
            logger.info("--- Scan Finished ---")
        except Exception as e:
            logger.error(f"Scan Error: {e}")
            login_115()

        time.sleep(SCAN_INTERVAL)

@app.route('/')
def index():
    return "115 Music Strm Service is Running."

@app.route('/play/<pickcode>/<filename>')
def play_redirect(pickcode, filename):
    global fs
    try:
        if fs is None: login_115()
        url = fs.get_url(pickcode)
        return redirect(url, code=302)
    except Exception as e:
        logger.error(f"Get Link Error: {e}")
        login_115()
        return f"Error getting link: {e}", 500

if __name__ == '__main__':
    t = threading.Thread(target=scanner_task, daemon=True)
    t.start()
    app.run(host='0.0.0.0', port=8000)
